### ISSUE TITLE
Setting opacity to 0 

### ISSUE THREAD

**Issue by mrjjwright** [picodom/picodom#18]
I set opacity to 0 as follows:

`h(
          "div",
          {
            class: "",
            style: { width: 15, height: 15, opacity: 0 },
            oninsert: function(el) {
              checkEl = el;
            }
          },
          "✔"
        )`

Picodom is not outputting an opacity css style prop on the element.  If I set it to 0.1 or higher it does.

**Comment by jbucaran** [comment]
@mrjjwright Interesting! I think this might be a bug. I'll keep you posted on this.

**Comment by mrjjwright** [comment]
Thanks, also it appears that strings like “0” work, which might be a clue.

**Comment by yepbug** [comment]
I think [this line](https://github.com/picodom/picodom/blob/master/src/patch.js#L151) is why there is a bug (`value['opacity']` is 0, which is a false value) . And change this line to `element.style[i] = String(value[i]) || "";` can fix this.

**Comment by jbucaran** [comment]
Thanks @yepbug. Yes, that should do it. 

@mrjjwright Just curious. Why were you using a number instead of a string?

**Comment by acstll** [comment]
Here's some interesting discussion: https://github.com/w3c/webcomponents/issues/519

I think doing `String(value[i]) || ""` might not be the best answer, because other values like `false` or `null` would be stringified as well and you don't want `opacity = "null"`. Maybe something like testing against `value[i]` not being null or undefined?:

```js
element.style[i] = value[i] != null ? value[i] || ""
```
The most important thing would be to settle on the API first, should attributes accept only strings? how should other types be handled? And make it clear on the documentation.

**Comment by jbucaran** [comment]
@acstll Why would you use a number instead of a string again?

**Comment by acstll** [comment]
> @acstll Why would you use a number instead of a string again?

I can imagine getting the value out of a computation, for example, so you just use that. You do something like `{ opacity: result }`; it's just easier. One can always do `{ opacity: String(result) }` I guess.

I'm in favor of only accepting strings as attribute values, so this here wouldn't be a bug. And I'm just giving my opinion here I'm not even using picodom myself :-)

**Comment by mindplay-dk** [comment]
IMO, disallowing `number` doesn't make sense - this is Javascript, and people *will* use numbers regardless of any specification or documentation. What would you do, throw an `Error`? That would likely be surprising to JS developers who naturally expect scripts to handle different types dynamically - it would just be pedantic.

IMO, the challenges here are minimal - handling numbers poses no real difficulty, so there's no practical reason to create problems or surprises by disallowing numbers: [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by JorgeBucaran** [comment]
Sounds good, but we could argue that picodom shouldn't even bother with inline styles (allow setting style attribute only, which is currently impossible).

Inline styles are slow and this is a good chance to use CSS-in-JS solutions.

**Comment by mindplay-dk** [comment]
IMO, support for inline styles is pretty universal across JSX implementations - it would suck not to have this, and (regardless of micro performance concerns) it already provides a basic CSS-in-JS solution, since you can simply create objects/modules with reusable CSS properties.

If someone has extreme performance requirements, they can either use regular CSS or a CSS-in-JS solution, there are plenty of options, but basic object-to-`style` property binding is pretty universal and likely a reasonably natural expectation for most people.

**Comment by acstll** [comment]
I'm gonna PR this so we can discuss over a possible solution and not about things sucking or not. ✌️

**Comment by mindplay-dk** [comment]
Good call 😊

**Comment by mindplay-dk** [comment]
The PR was merged, so we can close this?
