### ISSUE TITLE
Style attribute isn’t set in DOM

### ISSUE THREAD

**Issue by arturi** [picodom/picodom#25]
Hi! Thank you for the lib!

Ran into an issue with a missing `style` tag:

```js
const { h } = require('picodom')
const hyperx = require('hyperx')
const html = hyperx(h, {attrToProp: false})

const a = html`<div style="height: 100%; background-color: red;">123</div>`
console.log(a)
```

console:
<img width="389" alt="screen shot 2017-08-27 at 9 45 02 pm" src="https://user-images.githubusercontent.com/1199054/29752993-06124ba2-8b71-11e7-90af-2405305f5055.png">

DOM:
```html
<div>123</div>
```

Tried in the example pen (thought maybe hyperx is to blame), same thing:

https://codepen.io/anon/pen/jLvjOQ?editors=0110

**Comment by jbucaran** [comment]
@arturi Yep, looks like we only accept style as an object.

**Comment by arturi** [comment]
Yeah, so it’s [same deal as with React](https://facebook.github.io/react/docs/dom-elements.html#style). Do you think it would be worth the trouble to support the string?

**Comment by jbucaran** [comment]
> The style attribute accepts a JavaScript object with camelCased properties rather than a CSS string. This is consistent with the DOM style JavaScript property, is more efficient, and prevents XSS security holes.

@arturi Hmm, sounds like a good idea to not support this.

But if you must, you can always:

```jsx
Object.keys(style).reduce((styleStr, key) => 
  `${styleStr}${key.replace(/[A-Z]/g, "-$&").toLowerCase()}:${styleStr[key]};`, "")
```


Also consider [picostyle](https://github.com/picostyle/picostyle). 😄

**Comment by arturi** [comment]
Thanks! Yeah, I just saw that [Preact supports it](https://github.com/developit/preact/blob/33fc697ac11762a1cb6e71e9847670d047af7ce5/src/dom/index.js#L49-L60) and it got me thinking.

**Comment by jbucaran** [comment]
@arturi Why are using a style string anyway? Just curious. Very. 😄

**Comment by arturi** [comment]
Well, I could just as easily use an object, I suppose, it just feels more natural, like it’s regular HTML and it’s the same style as I would set in dev tools: https://github.com/transloadit/uppy/blob/5d36e25772665c34ef3fdc0b408be55fde853d7d/src/plugins/Informer.js#L51-L56 and https://github.com/transloadit/uppy/blob/5d36e25772665c34ef3fdc0b408be55fde853d7d/src/plugins/StatusBar/StatusBar.js#L112.

**Comment by jbucaran** [comment]
>  I could just as easily use an object.

Then you should. 😄 

I've actually considered removing inline style support entirely, but that's maybe too much. 

---

Closing as wontfix.

**Comment by arturi** [comment]
Fair enough. Another answer to “why”: all my current templates are using inline-styles, so I wanted to switch from `yo-yo` to `picodom`, and it just worked, apart from this.

**Comment by jbucaran** [comment]
> This is consistent with the DOM style JavaScript property

This sounds good, but

> , is more efficient, and prevents XSS security holes.

is what convinced me to not bring this into Picodom.

Thanks! 😄

**Comment by cjh9** [comment]
@arturi I really needed inline styles, because I'm creating a virtual-dom tree from the output of katex.

So I just changed line 60 in `patch.js`, `setElementProp` to:
``` js
    if( typeof(value) === 'string'){
       element.style.cssText = value;
    }
    else{
      for (var name in merge(oldValue, (value = value || {}))) {
        element.style[name] = value[name] || ""
      }
    }
```

and inline style-strings work.

**Comment by JorgeBucaran** [comment]
@cjh9 Pet peeve: `typeof` is not a function ;)

**Comment by cjh9** [comment]
@JorgeBucaran Right, but it works because the parenthesis just return the value, and the operator requires no space. You earn something new everyday, thanx :)

**Comment by JorgeBucaran** [comment]
@cjh9 https://github.com/prettier/prettier

**Comment by mindplay-dk** [comment]
FWIW, I'm in favor of supporting `style` as a `string` - I find it surprising when standard DOM-attributes can't be initialized the way you'd initialize a DOM-attribute anywhere else.

**Comment by JorgeBucaran** [comment]
I find life without surprises rather boring.

**Comment by leeoniya** [comment]
> I find life without surprises rather boring.

this is more "surprise, a flat tire!" than "surprise, a trip to italy!". to be fair, i *do* prefer all my network switches to randomly drop packets; i haven't bought a boring, predictable switch in years. 😆

**Comment by JorgeBucaran** [comment]
https://reactjs.org/docs/dom-elements.html#style

**Comment by mindplay-dk** [comment]
Having thought more about this, I've changed my mind.

One reason *not* to support strings, is it makes it impossible to incrementally patch CSS properties, since you can't directly diff between a string and an object - or, at least not without rolling out a CSS parser for the string first, which is likely out of the question. So, if we support strings, we'll invite weird edge-cases where the style-property changes to/from a string/object.

Another argument is why use strings in the first place? Is there ever a good reason to do that?

The use of `style` in the first place, is likely mostly interesting for things like toggling state (collapse/expand, etc.) and hopefully never as a means of actually styling UI elements - for that, a CSS-in-JS framework, or just a good'ol CSS file and the `class` attribute, are likely much preferable. It's likely not worth sweating over?

**Comment by cjh9** [comment]
@mindplay-dk Sounds very ambitious to incrementally patch css properties 😛  If you set the background of `body` to blue and then try to do `document.body.style.background = 'blue';` in the console, the browser will not make any dom-changes. 

So a simple css parser is perhaps just`cssstring.split(/;/).map((i)=>i.split(/:/))`?

My development cycle is not going to the editor and change css, I always sit in the inspector and increment/decrement css properties with cmd+shift+up etc. Then I finally copy the finished css to the editor so I prefer not using objects since it slows down the dev. cycle always having to convert the thing...
