### ISSUE TITLE
Documentation for routing.

### ISSUE THREAD

**Issue by andrewfluck** [picodom/picodom#28]
Picodom is a great VDom library, but it still needs routing. I was hoping to remedy this by using a 3rd party router, but I haven't had any luck with this. Can someone demonstrate how to achieve routing in this library?

**Comment by jbucaran** [comment]
Do you guys have any ideas? @SkaterDad @zaceno

**Comment by SkaterDad** [comment]
I haven't used `picodom` by itself yet, but I'll do some experimenting.

**Comment by SkaterDad** [comment]
Here's a Codepen example using `univeral-router`, since it seems very popular on Github & npm.  It's got a weird API, in my opinion, but it works.

This example has 4 routes:  page 1, page 2, page 3 and 404 not found.
Page 3 uses a route parameter.

https://codepen.io/anon/pen/eGmmBp?editors=0010

(Credit:  This demo is heavily inspired/copied from the React demo here:  https://jsfiddle.net/frenzzy/fr1q4gne/ )

**Comment by andrewfluck** [comment]
Thank you, I will take a look and modify the example according to my needs. I'll try making my own sample using page.js, another popular routing solution.

**Comment by JorgeBucaran** [comment]
Hi @andrewfluck, any progress with this? 👋

**Comment by andrewfluck** [comment]
Honestly I'm just using Hyperapp now, I figured since it comes with a bit more I might make a logical decision and switch over

**Comment by andrewfluck** [comment]
Why reinvent the wheel

**Comment by JorgeBucaran** [comment]
Sounds good @andrewfluck, I'll close here then.
